title: Transfer Easy Cab â€“ Private Transfers Blog
description: description: Private transfer guides from Paris airports to Disneyland Paris, city hotels, and long-distance destinations. Expert tips on Paris Disney transfers, airport taxi services, and private chauffeurs.
theme: just-the-docs

# URL de base pour GitHub Pages
baseurl: "/transfereasycab"

# Activation du TOC automatique
just_the_docs:
  show_sidebar: true
  heading_levels: 2,3
